{% set xorg_name = "xorg-cf-files" %}
{% set xorg_category = "util" %}
{% set name = "xorg-cf-files" %}
{% set version = "1.0.9" %}
{% set sha256 = "07716eb1fe1fd1f8a1d6588457db0101cae70cb896d49dc65978c97b148ce976" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - no-lib64.patch

build:
  number: 0

requirements:
  build:
    - pkg-config                   # [unix]
    - m2-pkg-config                # [win]
    - m2-base                      # [win]
    - meson
    - ninja
    - {{ compiler("c") }}          # [unix]
    - {{ stdlib("c") }}            # [unix]
    - {{ compiler("m2w64_c") }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
  host:
    - xorg-font-util
    - xorg-util-macros

test:
  commands:

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Configuration files for the X.org "imake" utility.

extra:
  recipe-maintainers:
    - pkgw
