appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Mp+koAO9/gMI611/amlbJPDiIXJ3OeOSZV3+3i+v08BswknDMbFb3T4+WGN8aAcN5OdGh+bjSKc1W9Ub3pPU9Nu4Neqi/kfGAKK50n+Ue+JmpXZfOp9jPaeMSQmtqF9wi4YA6jVJOjm/DU2pt56RBRYhpuTgPvhPC0ns+FPX4wkj2BGQuIrt6ofx9AbYoJPSmnZ/Fd4alxyemqXV2+kzhWu84lz377Z9KKgA4un0MkJF+fd6TmkGWn/4qoL1Gzj0ObS/5j+LEGQX86HsJd3q7U4p3nUCHTeYopo2gmS8DzoropSiwu+YRd9/VFNxeG6uoP/+aiyiamAc9VMkWbBTuYMbisYShTGc1NCgru1LMcnAW0Vit75cdJ1JExbfdAtcgi1NINeKWXRa10nNG7BSUslP1dcQOs6iUrNMawzgjKO/Wv7n3cJhZPY+lfpmKAeB5CgN0zdufITnZiu90UzWRee3t/jn+K++8aviExo62ftKiUkz31HlGPUBThSnjI3cENL7JfLtZnX4ZO6ZdmK4eJRzyRGXrzkHmVwt+hTkvkz167acP4KOiVO0gZJrgHF4s22zh9Bofqnq0s+xO7teKdGFJZaRqLJGCti1Wb1Xq99OGQJw7UNZxNjos6X5jUoQiYacgeixauSQWkh4xI1N/yb15WYPETp2IZFPYwWTe9w=}
conda_forge_output_validation: true
