travis:
  secure:
    BINSTAR_TOKEN: nJlKv8udluyrnsjQwPUVdn+kebZyUn1yPhIYjT3fgFPJqffXtq1tCwHbl731Tjkuwxb64XwP75Bh9wUjl+033DbODfE90xY3pOvQ7nq4fJAeCqOLqbkuE79O5xmoFiXTm3RtJSvCRg+L57FE9+WDgZhE7y2p5baD8MsbHct47lhiJxeEPZNOxhdAZomEplvX1ZlK1jACsk0JS+8U6jzxsEUv6BWcbkw4WuAmaITgFBkHVUjToeFsPJz2BWO4zPPsbalf1QGz8CFh64zh7n+e1NmX19TFARDCk7CP59Z0ikt11IJy4lYGdW4dEm6sjZ8A9KoN22HlzvNZcZLCeCxkNKwcgERvykyj+k26qwQ/GILN1HjwUHc/4Wk7gDIVb9eQ/WgZV9yezBZ/cbhwf7JcQSsQrID8NYcktaMrCbAHcjhH6Oah9AIs0GHXNzhBpqKpz8KJ2LPXsS15nV9X9w06dojT/XpjY2a3YtxZ/5DZaPQi5DVtr4+Eboj6u5dGbP/WZf3L9DDEJjkwE5ZMnNkeRu424vjUiP9YxlYS23vMN8LFeMPFlDxozULbLTem5lFL5OBWEjqT3QtTeCDrkswWbjj1j1JNJadQp3iLC+n8CI4mhoY4bZqWxhWDKEGT+fM/i7uW6nt2IaXX+jwJHXea9SmLbWjHesJ0qEa+/eeYaoc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
